In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('amazon_laptop_1.csv')

In [3]:
df.head(4)

,product_title,rating,total_rating,price,next_month_bought,offer,mrp,product_details_dict,brand,model_name,screen_size,colour,hard_disk_size,cpu_model,ram,os,special_features,graphics_card,about,technical_details_dict
0,"Lenovo Yoga Slim 7, Intel Core Ultra 5 125H, 1...",4.3,(63),"85,990.",NaN,-28%,"₹81,990","{'Brand': 'Lenovo', 'Model Name': 'Yoga Slim 7...",Lenovo,Yoga Slim 7,14,Luna Grey,512 GB,Intel Core Ultra 5,16 GB,Windows 11 Home,"Anti Glare Coating, Backlit Keyboard, HD Audio",Integrated,About this itemAI Enabled Processor: Intel Cor...,"{'Brand': '\u200eLenovo', 'Manufacturer': '\u2..."
1,Lenovo V15 G4 AMD Ryzen 5 7520U 15.6 inch FHD ...,4.0,(313),"38,000.",500+ boughtin past month,-27%,"₹39,999","{'Brand': 'Lenovo', 'Model Name': 'Lenovo V15'...",Lenovo,Lenovo V15,15.6 Inches,Gray,512 GB,Ryzen 5,16 GB,Windows 11,HD Audio,Integrated,About this itemProcessor: AMD Ryzen 5 7520U pr...,"{'Brand': '\u200eLenovo', 'Manufacturer': '\u2..."
2,"BrowseBook 14.1"" FHD IPS Laptop | Best Student...",3.1,(62),"16,990.",200+ boughtin past month,-60%,"₹12,090","{'Brand': 'Neopticon', 'Model Name': 'BrowseBo...",Neopticon,BrowseBook,14.1 Inches,Gray,128 GB,Celeron N4020,4 GB,Windows 11 Home,"HD Audio, Memory Card Slot",Integrated,About this itemFull HD IPS Display: The 14.1-i...,"{'Brand': '\u200eNeopticon', 'Manufacturer': '..."
3,"acer Aspire Lite, AMD Ryzen 3-7330U, 16GB RAM,...",3.9,"(2,071)","24,490.",400+ boughtin past month,-38%,"₹30,990","{'Brand': 'acer', 'Model Name': 'Aspire Lite',...",acer,Aspire Lite,15.6 Inches,Steel Gray,512 GB,Ryzen 3,16 GB,Windows 11 Home,Lightweight,Integrated,About this itemProcessor: AMD Ryzen 3 7330U pr...,"{'Brand': '\u200eacer', 'Manufacturer': '\u200..."

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_title           22 non-null     object
 1   rating                  22 non-null     float64
 2   total_rating            22 non-null     object
 3   price                   22 non-null     object
 4   next_month_bought       18 non-null     object
 5   offer                   21 non-null     object
 6   mrp                     21 non-null     object
 7   product_details_dict    22 non-null     object
 8   brand                   22 non-null     object
 9   model_name              22 non-null     object
 10  screen_size             22 non-null     object
 11  colour                  22 non-null     object
 12  hard_disk_size          22 non-null     object
 13  cpu_model               22 non-null     object
 14  ram                     22 non-null     object
 15  os                      22 non-null     object
 16  special_features        22 non-null     object
 17  graphics_card           22 non-null     object
 18  about                   22 non-null     object
 19  technical_details_dict  22 non-null     object
dtypes: float64(1), object(19)
memory usage: 3.6+ KB

In [5]:
df.shape

(22, 20)

In [6]:
df.describe()

          rating
count  22.000000
mean    3.922727
std     0.395127
min     3.100000
25%     3.725000
50%     3.950000
75%     4.175000
max     5.000000

In [7]:
df.columns=df.columns.str.strip()

In [8]:
df.duplicated().sum()

0

In [9]:
text_columns=df.select_dtypes(include='object')

In [10]:
#to remove the extra space
for col in text_columns:
    df[col]=df[col].str.strip()

In [11]:
for col in text_columns:
    df[col]=df[col].fillna('Unknown')

In [12]:
num_col=df.select_dtypes(include='number')

In [13]:
for col in num_col:
    df[col]=df[col].fillna(0)

In [14]:
df.head(3)

,product_title,rating,total_rating,price,next_month_bought,offer,mrp,product_details_dict,brand,model_name,screen_size,colour,hard_disk_size,cpu_model,ram,os,special_features,graphics_card,about,technical_details_dict
0,"Lenovo Yoga Slim 7, Intel Core Ultra 5 125H, 1...",4.3,(63),"85,990.",Unknown,-28%,"₹81,990","{'Brand': 'Lenovo', 'Model Name': 'Yoga Slim 7...",Lenovo,Yoga Slim 7,14,Luna Grey,512 GB,Intel Core Ultra 5,16 GB,Windows 11 Home,"Anti Glare Coating, Backlit Keyboard, HD Audio",Integrated,About this itemAI Enabled Processor: Intel Cor...,"{'Brand': '\u200eLenovo', 'Manufacturer': '\u2..."
1,Lenovo V15 G4 AMD Ryzen 5 7520U 15.6 inch FHD ...,4.0,(313),"38,000.",500+ boughtin past month,-27%,"₹39,999","{'Brand': 'Lenovo', 'Model Name': 'Lenovo V15'...",Lenovo,Lenovo V15,15.6 Inches,Gray,512 GB,Ryzen 5,16 GB,Windows 11,HD Audio,Integrated,About this itemProcessor: AMD Ryzen 5 7520U pr...,"{'Brand': '\u200eLenovo', 'Manufacturer': '\u2..."
2,"BrowseBook 14.1"" FHD IPS Laptop | Best Student...",3.1,(62),"16,990.",200+ boughtin past month,-60%,"₹12,090","{'Brand': 'Neopticon', 'Model Name': 'BrowseBo...",Neopticon,BrowseBook,14.1 Inches,Gray,128 GB,Celeron N4020,4 GB,Windows 11 Home,"HD Audio, Memory Card Slot",Integrated,About this itemFull HD IPS Display: The 14.1-i...,"{'Brand': '\u200eNeopticon', 'Manufacturer': '..."

In [15]:
df=df.drop(columns=['product_title','mrp','about','technical_details_dict'])

In [16]:
print(df['rating'].min())
print(df['rating'].max())

3.1
5.0

In [17]:
df['total_rating']=df['total_rating'].str.replace('(','',regex=False).str.replace(',','',regex=False).str.replace(')','',regex=False)

In [18]:
df['total_rating'].astype(int)

0       63
1      313
2       62
3     2071
4       48
5      614
6       10
7        5
8      766
9      818
10      56
11      70
12      60
13     964
14     100
15     347
16       1
17     614
18     818
19    2071
20      48
21      32
Name: total_rating, dtype: int32

In [19]:
df['price']=df['price'].str.replace(',','',regex=False)

In [20]:
df['price'].astype(float).unique()

array([ 85990.,  38000.,  16990.,  24490.,  99990.,  71800.,  36990.,
       103990.,  58490.,  26980.,  41890.,  49990.,  86990.,  40990.,
        42990.,  65990.,  72390.,  26490.,  34320., 114990.,  56501.])

In [21]:
df['next_month_bought'].unique()

array(['Unknown', '500+ boughtin past month', '200+ boughtin past month',
       '400+ boughtin past month', '50+ boughtin past month',
       '100+ boughtin past month', '300+ boughtin past month'],
      dtype=object)

In [22]:
p=df[df['next_month_bought']=='Unknown']
p.index
for i in p.index:
    df.loc[i,'next_month_bought']='0'

In [23]:
df['next_month_bought'].unique()

array(['0', '500+ boughtin past month', '200+ boughtin past month',
       '400+ boughtin past month', '50+ boughtin past month',
       '100+ boughtin past month', '300+ boughtin past month'],
      dtype=object)

In [24]:
df['next_month_bought']=df['next_month_bought'].str[:5].str.replace(r'[+b]','',regex=True).str.strip()

In [25]:
df['next_month_bought'].astype(int).unique()

array([  0, 500, 200, 400,  50, 100, 300])

In [26]:
df[df['offer']=='Unknown']
df.loc[19,'offer']='0'

In [27]:
df['offer']=df['offer'].str.replace(r'[-%]','',regex=True)

In [28]:
df['offer'].astype(int).unique()

array([28, 27, 60, 38, 17, 19, 13, 18, 26, 47, 43, 24, 20, 15,  0, 34])

In [29]:
df.head(3)

,rating,total_rating,price,next_month_bought,offer,product_details_dict,brand,model_name,screen_size,colour,hard_disk_size,cpu_model,ram,os,special_features,graphics_card
0,4.3,63,85990.,0,28,"{'Brand': 'Lenovo', 'Model Name': 'Yoga Slim 7...",Lenovo,Yoga Slim 7,14,Luna Grey,512 GB,Intel Core Ultra 5,16 GB,Windows 11 Home,"Anti Glare Coating, Backlit Keyboard, HD Audio",Integrated
1,4.0,313,38000.,500,27,"{'Brand': 'Lenovo', 'Model Name': 'Lenovo V15'...",Lenovo,Lenovo V15,15.6 Inches,Gray,512 GB,Ryzen 5,16 GB,Windows 11,HD Audio,Integrated
2,3.1,62,16990.,200,60,"{'Brand': 'Neopticon', 'Model Name': 'BrowseBo...",Neopticon,BrowseBook,14.1 Inches,Gray,128 GB,Celeron N4020,4 GB,Windows 11 Home,"HD Audio, Memory Card Slot",Integrated

In [30]:
df=df.drop(columns=['product_details_dict'])

In [31]:
df['brand'].unique()

array(['Lenovo', 'Neopticon', 'acer', 'ASUS', 'HP', 'Dell'], dtype=object)

In [32]:
df['model_name'].unique()

array(['Yoga Slim 7', 'Lenovo V15', 'BrowseBook', 'Aspire Lite',
       'ASUS Vivobook 16', 'TUF Gaming F15', 'DQ3149TU',
       'HP Gaming Laptop', 'HP Laptop', 'Aspire 3', 'Lenovo V14',
       'ThinkBook 16', 'ASUS TUF Gaming A16', 'Inspiron',
       'IdeaPad Slim 3', 'ASUS TUF Gaming A15', 'E14 Gen 6'], dtype=object)

In [33]:
df['screen_size'].unique()

array(['14', '15.6 Inches', '14.1 Inches', '16 Inches', '14 Inches',
       '39.6 Centimetres', '15.3 Inches', '15 Inches'], dtype=object)

In [34]:
# df['screen_size'].str.replace(r'\D','',regex=True) only foe numbers

In [35]:
df['screen_size']=df['screen_size'].str.extract(r'(\d+\.?\d*)')[0]

In [36]:
df=df.rename(columns={'screen_size':'screen_size(inches)','ram':'ram(GB)'})

In [37]:
df['colour'].unique()

array(['Luna Grey', 'Gray', 'Steel Gray', 'Black | Core 7 240H',
       'Black, R7 | RTX 3050', 'Black', 'Mica Silver', 'Silver',
       'Iron Grey', 'R7 7735HS', 'Mecha Gray', 'Natural Silver', 'Blue',
       'Graphite Black', '2024 Aura | Ultra 7 258V'], dtype=object)

In [38]:
df['hard_disk_size'].unique()

array(['512 GB', '128 GB', '1 TB'], dtype=object)

In [39]:
df['cpu_model'].unique()

array(['Intel Core Ultra 5', 'Ryzen 5', 'Celeron N4020', 'Ryzen 3',
       'Intel Core 7', 'AMD Ryzen 7', 'Celeron', 'Core i7', 'Core i5',
       'Others', 'Core i3', 'Ryzen 7', 'Core i3 Family', 'Intel Core i7',
       'Intel Core Ultra 7'], dtype=object)

In [40]:
df['os'].unique()

array(['Windows 11 Home', 'Windows 11'], dtype=object)

In [41]:
df['graphics_card'].unique()

array(['Integrated', 'Dedicated'], dtype=object)

In [43]:
df['ram(GB)']=df['ram(GB)'].str.replace(r'\D','',regex=True)

In [45]:
df['ram(GB)'].astype(int)

0     16
1     16
2      4
3     16
4     16
5     16
6      8
7     24
8     16
9      8
10     8
11    16
12    16
13    12
14    16
15    16
16    24
17    16
18    12
19    16
20    32
21    16
Name: ram(GB), dtype: int32

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   rating               22 non-null     float64
 1   total_rating         22 non-null     object
 2   price                22 non-null     object
 3   next_month_bought    22 non-null     object
 4   offer                22 non-null     object
 5   brand                22 non-null     object
 6   model_name           22 non-null     object
 7   screen_size(inches)  22 non-null     object
 8   colour               22 non-null     object
 9   hard_disk_size       22 non-null     object
 10  cpu_model            22 non-null     object
 11  ram(GB)              22 non-null     object
 12  os                   22 non-null     object
 13  special_features     22 non-null     object
 14  graphics_card        22 non-null     object
dtypes: float64(1), object(14)
memory usage: 2.7+ KB

In [ ]:
df.to_csv('