In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
ds=pd.read_csv('my_file (1).csv')

In [3]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Rank                              20 non-null     int64
 1   Peak                              9 non-null      object
 2   All Time Peak                     6 non-null      object
 3   Actual gross                      20 non-null     object
 4   Adjusted gross (in 2022 dollars)  20 non-null     object
 5   Artist                            20 non-null     object
 6   Tour title                        20 non-null     object
 7   Year(s)                           20 non-null     object
 8   Shows                             20 non-null     int64
 9   Average gross                     20 non-null     object
 10  Ref.                              20 non-null     object
dtypes: int64(2), object(9)
memory usage: 1.8+ KB

In [4]:
ds.shape

(20, 11)

In [5]:
ds.head()

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]

In [6]:
ds.describe()

            Rank       Shows
count  20.000000   20.000000
mean   10.450000  110.000000
std     5.942488   66.507617
min     1.000000   41.000000
25%     5.750000   59.000000
50%    10.500000   87.000000
75%    15.250000  134.500000
max    20.000000  325.000000

In [7]:
ds.columns=ds.columns.str.strip()

In [8]:
ds.duplicated().sum()

0

In [9]:
ds.columns

Index(['Rank', 'Peak', 'All Time Peak', 'Actual gross',
       'Adjusted gross (in 2022 dollars)', 'Artist', 'Tour title', 'Year(s)',
       'Shows', 'Average gross', 'Ref.'],
      dtype='object')

In [10]:
#To remove the extra sppace from text
text_columns=ds.select_dtypes(include='object').columns

In [11]:
for col in text_columns:
    ds[col]=ds[col].str.strip()

In [12]:
#Missing values checking
# for col in text_columns:
    # print(ds[ds[col].isna()])

In [13]:
#missing values handling
for col in text_columns:
    ds[col]=ds[col].fillna('Unknown')

In [14]:
ds.isna().sum()

Rank                                0
Peak                                0
All Time Peak                       0
Actual gross                        0
Adjusted gross (in 2022 dollars)    0
Artist                              0
Tour title                          0
Year(s)                             0
Shows                               0
Average gross                       0
Ref.                                0
dtype: int64

In [15]:
ds.select_dtypes(include='number').columns

Index(['Rank', 'Shows'], dtype='object')

In [16]:
num_columns=ds.select_dtypes(include='number').columns

In [17]:
ds[num_columns]=ds[num_columns].fillna(0)

In [18]:
#real names of columns
print(type(ds))
print(list(ds.columns))

<class 'pandas.core.frame.DataFrame'>
['Rank', 'Peak', 'All Time Peak', 'Actual\xa0gross', 'Adjusted\xa0gross (in 2022 dollars)', 'Artist', 'Tour title', 'Year(s)', 'Shows', 'Average gross', 'Ref.']

In [19]:
money_columns=[ 'Actual\xa0gross','Adjusted\xa0gross (in 2022 dollars)','Average gross']

In [20]:
for col in money_columns:
    ds[col]=(ds[col].str.replace('$','',regex=False).str.replace(',','',regex=False))
    ds[col]=pd.to_numeric(ds[col],errors='coerce')

In [23]:
ds['Actual\xa0gross']=ds['Actual\xa0gross'].fillna(0)

In [24]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Rank                              20 non-null     int64
 1   Peak                              20 non-null     object
 2   All Time Peak                     20 non-null     object
 3   Actual gross                      20 non-null     float64
 4   Adjusted gross (in 2022 dollars)  20 non-null     int64
 5   Artist                            20 non-null     object
 6   Tour title                        20 non-null     object
 7   Year(s)                           20 non-null     object
 8   Shows                             20 non-null     int64
 9   Average gross                     20 non-null     int64
 10  Ref.                              20 non-null     object
dtypes: float64(1), int64(4), object(6)
memory usage: 1.8+ KB

In [25]:
ds.to_csv('D:\Github\python-data-preprocessing\Messy_file_data/cleaned_file.csv')