In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
ds=pd.read_csv('Messy_Employee_dataset.csv')

In [3]:
ds.head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False

In [4]:
ds.tail()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
1015,EMP2015,David,Miller,30.0,HR-California,Active,8/19/2023,NaN,david.miller@example.com,-3546212759,Good,True
1016,EMP2016,David,Johnson,30.0,Cloud Tech-Texas,Inactive,11/7/2021,100215.06,david.johnson@example.com,-2508261122,Good,True
1017,EMP2017,Charlie,Williams,40.0,Finance-New York,Active,10/4/2023,114587.11,charlie.williams@example.com,-1261632487,Average,False
1018,EMP2018,Alice,Garcia,30.0,HR-Florida,Inactive,12/16/2024,71318.79,alice.garcia@example.com,-8995729892,Good,True
1019,EMP2019,Heidi,Jones,30.0,DevOps-Illinois,Pending,2/22/2021,77764.24,heidi.jones@example.com,-7629745492,Average,False

In [5]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   object
 1   First_Name         1020 non-null   object
 2   Last_Name          1020 non-null   object
 3   Age                809 non-null    float64
 4   Department_Region  1020 non-null   object
 5   Status             1020 non-null   object
 6   Join_Date          1020 non-null   object
 7   Salary             996 non-null    float64
 8   Email              1020 non-null   object
 9   Phone              1020 non-null   int64
 10  Performance_Score  1020 non-null   object
 11  Remote_Work        1020 non-null   bool
dtypes: bool(1), float64(2), int64(1), object(8)
memory usage: 88.8+ KB

In [6]:
ds.isna().sum()

Employee_ID            0
First_Name             0
Last_Name              0
Age                  211
Department_Region      0
Status                 0
Join_Date              0
Salary                24
Email                  0
Phone                  0
Performance_Score      0
Remote_Work            0
dtype: int64

In [7]:
ds.duplicated().sum()

0

In [8]:
m=ds[ds['Age'].isna()]
# ds.loc(m,'First_Name')
m[['Employee_ID','First_Name','Last_Name','Age','Department_Region','Salary']]

     Employee_ID First_Name Last_Name  Age  Department_Region     Salary
1        EMP1001        Bob     Brown  NaN      Finance-Texas   65304.66
2        EMP1002      Alice     Jones  NaN       Admin-Nevada   88145.90
6        EMP1006      Frank     Jones  NaN       Admin-Nevada   96288.43
9        EMP1009    Charlie   Johnson  NaN    DevOps-New York   76561.88
11       EMP1011      David     Davis  NaN  DevOps-California   84946.19
...          ...        ...       ...  ...                ...        ...
991      EMP1991      Heidi     Brown  NaN        Admin-Texas   86135.69
993      EMP1993      Grace     Brown  NaN      DevOps-Nevada   64045.36
1006     EMP2006      Grace     Brown  NaN        HR-Illinois   77821.79
1009     EMP2009      David    Garcia  NaN   Finance-Illinois   62603.98
1013     EMP2013        Eva  Williams  NaN        HR-Illinois  116680.63

[211 rows x 6 columns]

In [9]:
print(ds['Age'].max())
print(ds['Age'].min())
print(ds['Age'].mean())

40.0
25.0
32.48454882571075

In [10]:
ds['Age']=ds['Age'].fillna(ds["Age"].mean())

In [11]:
ds['Age'].isna().sum()

0

In [12]:
ds['Salary'].isna().sum()

24

In [13]:
print(ds['Salary'].max())
print(ds['Salary'].min())
print(ds['Salary'].mean())

119971.65
50047.32
85155.05639558233

In [14]:
s=ds[ds['Salary'].isna()]
s[['Employee_ID','First_Name','Last_Name','Age','Department_Region','Salary']]

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Salary
99,EMP1099,Eva,Jones,25.000000,Admin-California,NaN
289,EMP1289,Grace,Garcia,25.000000,Admin-New York,NaN
329,EMP1329,Heidi,Garcia,40.000000,Cloud Tech-Texas,NaN
344,EMP1344,Grace,Williams,30.000000,DevOps-Florida,NaN
398,EMP1398,Bob,Garcia,30.000000,Sales-New York,NaN
577,EMP1577,Frank,Miller,32.484549,Cloud Tech-Texas,NaN
582,EMP1582,Grace,Brown,40.000000,HR-Texas,NaN
619,EMP1619,Bob,Williams,25.000000,Finance-Nevada,NaN
636,EMP1636,Grace,Smith,35.000000,DevOps-Florida,NaN
677,EMP1677,Heidi,Garcia,35.000000,Cloud Tech-Florida,NaN
700,EMP1700,Heidi,Johnson,25.000000,DevOps-Illinois,NaN
770,EMP1770,Charlie,Jones,25.000000,Admin-New York,NaN
821,EMP1821,Grace,Brown,30.000000,HR-Texas,NaN
837,EMP1837,Eva,Jones,35.000000,Admin-Illinois,NaN
876,EMP1876,Alice,Johnson,30.000000,Cloud Tech-Nevada,NaN
899,EMP1899,David,Williams,30.000000,HR-California,NaN
936,EMP1936,Eva,Miller,40.000000,Sales-Nevada,NaN
940,EMP1940,Eva,Brown,40.000000,DevOps-Texas,NaN
948,EMP1948,Bob,Miller,40.000000,Finance-Texas,NaN
953,EMP1953,Alice,Brown,40.000000,Cloud Tech-California,NaN
956,EMP1956,David,Brown,32.484549,Sales-Texas,NaN
963,EMP1963,Eva,Davis,40.000000,Admin-Texas,NaN
1012,EMP2012,Grace,Miller,35.000000,DevOps-Florida,NaN
1015,EMP2015,David,Miller,30.000000,HR-California,NaN

In [15]:
ds['Salary']=ds['Salary'].fillna(ds['Salary'].mean())

In [16]:
ds.isna().sum()

Employee_ID          0
First_Name           0
Last_Name            0
Age                  0
Department_Region    0
Status               0
Join_Date            0
Salary               0
Email                0
Phone                0
Performance_Score    0
Remote_Work          0
dtype: int64

In [17]:
ds["Name"]=ds['First_Name']+'_'+ds['Last_Name']

In [18]:
ds

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work,Name
0,EMP1000,Bob,Davis,25.000000,DevOps-California,Active,4/2/2021,59767.650000,bob.davis@example.com,-1651623197,Average,True,Bob_Davis
1,EMP1001,Bob,Brown,32.484549,Finance-Texas,Active,7/10/2020,65304.660000,bob.brown@example.com,-1898471390,Excellent,True,Bob_Brown
2,EMP1002,Alice,Jones,32.484549,Admin-Nevada,Pending,12/7/2023,88145.900000,alice.jones@example.com,-5596363211,Good,True,Alice_Jones
3,EMP1003,Eva,Davis,25.000000,Admin-Nevada,Inactive,11/27/2021,69450.990000,eva.davis@example.com,-3476490784,Good,True,Eva_Davis
4,EMP1004,Frank,Williams,25.000000,Cloud Tech-Florida,Active,1/5/2022,109324.610000,frank.williams@example.com,-1586734256,Poor,False,Frank_Williams
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,EMP2015,David,Miller,30.000000,HR-California,Active,8/19/2023,85155.056396,david.miller@example.com,-3546212759,Good,True,David_Miller
1016,EMP2016,David,Johnson,30.000000,Cloud Tech-Texas,Inactive,11/7/2021,100215.060000,david.johnson@example.com,-2508261122,Good,True,David_Johnson
1017,EMP2017,Charlie,Williams,40.000000,Finance-New York,Active,10/4/2023,114587.110000,charlie.williams@example.com,-1261632487,Average,False,Charlie_Williams
1018,EMP2018,Alice,Garcia,30.000000,HR-Florida,Inactive,12/16/2024,71318.790000,alice.garcia@example.com,-8995729892,Good,True,Alice_Garcia
1019,EMP2019,Heidi,Jones,30.000000,DevOps-Illinois,Pending,2/22/2021,77764.240000,heidi.jones@example.com,-7629745492,Average,False,Heidi_Jones

In [19]:
ds=ds.drop(columns=['First_Name','Last_Name'])

In [20]:
ds['Phone']=ds['Phone'].replace('-','',regex=True)

In [21]:
mapping={True:1,
     False:0}
ds['Remote_Work']=ds['Remote_Work'].replace(mapping)

In [22]:
ds

,Employee_ID,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work,Name
0,EMP1000,25.000000,DevOps-California,Active,4/2/2021,59767.650000,bob.davis@example.com,-1651623197,Average,1,Bob_Davis
1,EMP1001,32.484549,Finance-Texas,Active,7/10/2020,65304.660000,bob.brown@example.com,-1898471390,Excellent,1,Bob_Brown
2,EMP1002,32.484549,Admin-Nevada,Pending,12/7/2023,88145.900000,alice.jones@example.com,-5596363211,Good,1,Alice_Jones
3,EMP1003,25.000000,Admin-Nevada,Inactive,11/27/2021,69450.990000,eva.davis@example.com,-3476490784,Good,1,Eva_Davis
4,EMP1004,25.000000,Cloud Tech-Florida,Active,1/5/2022,109324.610000,frank.williams@example.com,-1586734256,Poor,0,Frank_Williams
...,...,...,...,...,...,...,...,...,...,...,...
1015,EMP2015,30.000000,HR-California,Active,8/19/2023,85155.056396,david.miller@example.com,-3546212759,Good,1,David_Miller
1016,EMP2016,30.000000,Cloud Tech-Texas,Inactive,11/7/2021,100215.060000,david.johnson@example.com,-2508261122,Good,1,David_Johnson
1017,EMP2017,40.000000,Finance-New York,Active,10/4/2023,114587.110000,charlie.williams@example.com,-1261632487,Average,0,Charlie_Williams
1018,EMP2018,30.000000,HR-Florida,Inactive,12/16/2024,71318.790000,alice.garcia@example.com,-8995729892,Good,1,Alice_Garcia
1019,EMP2019,30.000000,DevOps-Illinois,Pending,2/22/2021,77764.240000,heidi.jones@example.com,-7629745492,Average,0,Heidi_Jones

In [23]:
ds.to_csv('Cleaned_employee_data.csv')