In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
movies=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_credits.csv')

In [3]:
#movies.head()
#credits.head()

In [4]:
#merge(join 2 dataset based on columns)
ds=pd.merge(movies,credits,left_on='id',right_on='movie_id',how='inner')

In [5]:
ds.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title_x', 'vote_average',
       'vote_count', 'movie_id', 'title_y', 'cast', 'crew'],
      dtype='object')

In [6]:
ds=ds[['id','title_x','genres','keywords','overview','production_companies','tagline','cast','crew']]

In [7]:
ds.rename(columns={'title_x':'Title'},inplace=True)

In [8]:
#Function which receives string of list of dict 
#converts to list and iterate all dict and returns comma seperated list of 'name' from dict
import ast #abstract syntax string
def get_names(mystring):
    geners=ast.literal_eval(mystring)
    words=[]
    for g in geners:
        words.append(g['name'])
    words=','.join(words)
    return words

In [9]:
ds['genres']=ds['genres'].apply(get_names)

In [10]:
ds['keywords']=ds['keywords'].apply(get_names)

In [11]:
ds['production_companies']=ds['production_companies'].apply(get_names)

In [12]:
ds['cast']=ds['cast'].apply(get_names)

In [13]:
ds['crew']=ds['crew'].apply(get_names)

In [14]:
ds.head()

,id,Title,genres,keywords,overview,production_companies,tagline,cast,crew
0,19995,Avatar,"Action,Adventure,Fantasy,Science Fiction","culture clash,future,space war,space colony,so...","In the 22nd century, a paraplegic Marine is di...","Ingenious Film Partners,Twentieth Century Fox ...",Enter the World of Pandora.,"Sam Worthington,Zoe Saldana,Sigourney Weaver,S...","Stephen E. Rivkin,Rick Carter,Christopher Boye..."
1,285,Pirates of the Caribbean: At World's End,"Adventure,Fantasy,Action","ocean,drug abuse,exotic island,east india trad...","Captain Barbossa, long believed to be dead, ha...","Walt Disney Pictures,Jerry Bruckheimer Films,S...","At the end of the world, the adventure begins.","Johnny Depp,Orlando Bloom,Keira Knightley,Stel...","Dariusz Wolski,Gore Verbinski,Jerry Bruckheime..."
2,206647,Spectre,"Action,Adventure,Crime","spy,based on novel,secret agent,sequel,mi6,bri...",A cryptic message from Bond’s past sends him o...,"Columbia Pictures,Danjaq,B24",A Plan No One Escapes,"Daniel Craig,Christoph Waltz,Léa Seydoux,Ralph...","Thomas Newman,Sam Mendes,Anna Pinnock,John Log..."
3,49026,The Dark Knight Rises,"Action,Crime,Drama,Thriller","dc comics,crime fighter,terrorist,secret ident...",Following the death of District Attorney Harve...,"Legendary Pictures,Warner Bros.,DC Entertainme...",The Legend Ends,"Christian Bale,Michael Caine,Gary Oldman,Anne ...","Hans Zimmer,Charles Roven,Christopher Nolan,Ch..."
4,49529,John Carter,"Action,Adventure,Science Fiction","based on novel,mars,medallion,space travel,pri...","John Carter is a war-weary, former military ca...",Walt Disney Pictures,"Lost in our world, found in another.","Taylor Kitsch,Lynn Collins,Samantha Morton,Wil...","Andrew Stanton,Andrew Stanton,John Lasseter,Co..."

In [15]:
ds.iloc[0]['overview']

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [16]:
def remove_spaces_with_comma(sentence):
    sentence=str(sentence)
    sentence=sentence.replace(',','')
    sentence=sentence.replace(' ',',')
    return sentence

In [17]:
ds['overview']=ds['overview'].apply(remove_spaces_with_comma)

In [18]:
ds.iloc[0]['tagline']

'Enter the World of Pandora.'

In [19]:
ds['tagline']=ds['tagline'].apply(remove_spaces_with_comma)

In [20]:
ds.head()

,id,Title,genres,keywords,overview,production_companies,tagline,cast,crew
0,19995,Avatar,"Action,Adventure,Fantasy,Science Fiction","culture clash,future,space war,space colony,so...","In,the,22nd,century,a,paraplegic,Marine,is,dis...","Ingenious Film Partners,Twentieth Century Fox ...","Enter,the,World,of,Pandora.","Sam Worthington,Zoe Saldana,Sigourney Weaver,S...","Stephen E. Rivkin,Rick Carter,Christopher Boye..."
1,285,Pirates of the Caribbean: At World's End,"Adventure,Fantasy,Action","ocean,drug abuse,exotic island,east india trad...","Captain,Barbossa,long,believed,to,be,dead,has,...","Walt Disney Pictures,Jerry Bruckheimer Films,S...","At,the,end,of,the,world,the,adventure,begins.","Johnny Depp,Orlando Bloom,Keira Knightley,Stel...","Dariusz Wolski,Gore Verbinski,Jerry Bruckheime..."
2,206647,Spectre,"Action,Adventure,Crime","spy,based on novel,secret agent,sequel,mi6,bri...","A,cryptic,message,from,Bond’s,past,sends,him,o...","Columbia Pictures,Danjaq,B24","A,Plan,No,One,Escapes","Daniel Craig,Christoph Waltz,Léa Seydoux,Ralph...","Thomas Newman,Sam Mendes,Anna Pinnock,John Log..."
3,49026,The Dark Knight Rises,"Action,Crime,Drama,Thriller","dc comics,crime fighter,terrorist,secret ident...","Following,the,death,of,District,Attorney,Harve...","Legendary Pictures,Warner Bros.,DC Entertainme...","The,Legend,Ends","Christian Bale,Michael Caine,Gary Oldman,Anne ...","Hans Zimmer,Charles Roven,Christopher Nolan,Ch..."
4,49529,John Carter,"Action,Adventure,Science Fiction","based on novel,mars,medallion,space travel,pri...","John,Carter,is,a,war-weary,former,military,cap...",Walt Disney Pictures,"Lost,in,our,world,found,in,another.","Taylor Kitsch,Lynn Collins,Samantha Morton,Wil...","Andrew Stanton,Andrew Stanton,John Lasseter,Co..."

In [21]:
ds['tags']=ds['genres']+','+ds['keywords']+','+ds['overview']+','+ds['production_companies']+','+ds['tagline']+','+ds['cast']+','+ds['crew']

In [22]:
ds.head()

,id,Title,genres,keywords,overview,production_companies,tagline,cast,crew,tags
0,19995,Avatar,"Action,Adventure,Fantasy,Science Fiction","culture clash,future,space war,space colony,so...","In,the,22nd,century,a,paraplegic,Marine,is,dis...","Ingenious Film Partners,Twentieth Century Fox ...","Enter,the,World,of,Pandora.","Sam Worthington,Zoe Saldana,Sigourney Weaver,S...","Stephen E. Rivkin,Rick Carter,Christopher Boye...","Action,Adventure,Fantasy,Science Fiction,cultu..."
1,285,Pirates of the Caribbean: At World's End,"Adventure,Fantasy,Action","ocean,drug abuse,exotic island,east india trad...","Captain,Barbossa,long,believed,to,be,dead,has,...","Walt Disney Pictures,Jerry Bruckheimer Films,S...","At,the,end,of,the,world,the,adventure,begins.","Johnny Depp,Orlando Bloom,Keira Knightley,Stel...","Dariusz Wolski,Gore Verbinski,Jerry Bruckheime...","Adventure,Fantasy,Action,ocean,drug abuse,exot..."
2,206647,Spectre,"Action,Adventure,Crime","spy,based on novel,secret agent,sequel,mi6,bri...","A,cryptic,message,from,Bond’s,past,sends,him,o...","Columbia Pictures,Danjaq,B24","A,Plan,No,One,Escapes","Daniel Craig,Christoph Waltz,Léa Seydoux,Ralph...","Thomas Newman,Sam Mendes,Anna Pinnock,John Log...","Action,Adventure,Crime,spy,based on novel,secr..."
3,49026,The Dark Knight Rises,"Action,Crime,Drama,Thriller","dc comics,crime fighter,terrorist,secret ident...","Following,the,death,of,District,Attorney,Harve...","Legendary Pictures,Warner Bros.,DC Entertainme...","The,Legend,Ends","Christian Bale,Michael Caine,Gary Oldman,Anne ...","Hans Zimmer,Charles Roven,Christopher Nolan,Ch...","Action,Crime,Drama,Thriller,dc comics,crime fi..."
4,49529,John Carter,"Action,Adventure,Science Fiction","based on novel,mars,medallion,space travel,pri...","John,Carter,is,a,war-weary,former,military,cap...",Walt Disney Pictures,"Lost,in,our,world,found,in,another.","Taylor Kitsch,Lynn Collins,Samantha Morton,Wil...","Andrew Stanton,Andrew Stanton,John Lasseter,Co...","Action,Adventure,Science Fiction,based on nove..."

In [23]:
ds['tags']=ds['tags'].apply(lambda val:val.lower())

In [24]:
ds=ds[['id','Title','tags']]

In [25]:
ds.head()

,id,Title,tags
0,19995,Avatar,"action,adventure,fantasy,science fiction,cultu..."
1,285,Pirates of the Caribbean: At World's End,"adventure,fantasy,action,ocean,drug abuse,exot..."
2,206647,Spectre,"action,adventure,crime,spy,based on novel,secr..."
3,49026,The Dark Knight Rises,"action,crime,drama,thriller,dc comics,crime fi..."
4,49529,John Carter,"action,adventure,science fiction,based on nove..."

In [26]:
def get_unique_words(original_string):
    # Step 1: Split, strip, and remove duplicates using set
    words = [word.strip() for word in original_string.split(',')]
    unique_words = list(set(words))
    # Optional: sort if you want consistent output
    unique_words.sort()
    # Step 2: Join back into a comma-separated string
    new_string = ','.join(unique_words)
    return new_string

In [27]:
ds['tags']=ds['tags'].apply(get_unique_words)

In [28]:
ds.head()

,id,Title,tags
0,19995,Avatar,"22nd,3d,a,action,addison teague,adrian fernand..."
1,285,Pirates of the Caribbean: At World's End,"action,adventure,aftercreditsstinger,afterlife..."
2,206647,Spectre,"a,abderrahim benkhayi,action,adam dale,adam mc..."
3,49026,The Dark Knight Rises,"a,aaron vexler,action,adam camacho,adam horton..."
4,49529,John Carter,"(mars),19th century,3d,a,action,adventure,ailb..."

In [29]:
import nltk
from nltk.corpus import stopwords

In [30]:
def remove_stop_words(text):
    # Get the English stopwords list
    stop_words = set(stopwords.words('english'))
    # Tokenize the sentence
    words = text.split(',')
    # Remove stopwords
    filtered_words = [word for word in words if word.lower() not in stop_words]
    # # Convert back to string
    filtered_text = ",".join(filtered_words)
    return filtered_text

In [31]:
ds['tags']=ds['tags'].apply(remove_stop_words)

In [32]:
ds['tags']=ds['tags'].apply(lambda val:val.replace(' ','_'))

In [33]:
ds.head()

,id,Title,tags
0,19995,Avatar,"22nd,3d,action,addison_teague,adrian_fernandes..."
1,285,Pirates of the Caribbean: At World's End,"action,adventure,aftercreditsstinger,afterlife..."
2,206647,Spectre,"abderrahim_benkhayi,action,adam_dale,adam_mcgr..."
3,49026,The Dark Knight Rises,"aaron_vexler,action,adam_camacho,adam_horton,a..."
4,49529,John Carter,"(mars),19th_century,3d,action,adventure,ailbhe..."

In [34]:
ds.shape

(4803, 3)

In [36]:
ds.to_csv("Cleaned_dataset.csv")