In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('dirty_cafe_sales.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [4]:
df.shape

(10000, 8)

In [5]:
df.describe()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_1961373,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

In [6]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [7]:
df=df.drop_duplicates()

In [8]:
df.duplicated().sum()

0

In [9]:
text_columns=df.select_dtypes(include='object')
text_columns

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [10]:
for col in text_columns:
    df[col]=df[col].str.strip()

In [11]:
for col in text_columns:
    print(f"{col} : {df[col].isna().sum()}")

Transaction ID : 0
Item : 333
Quantity : 138
Price Per Unit : 179
Total Spent : 173
Payment Method : 2579
Location : 3265
Transaction Date : 159

In [12]:
for col in text_columns:
    df[col]=df[col].fillna('Unknown')

In [13]:
df.head(3)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19

In [14]:
df['Transaction ID'].duplicated().sum()

0

In [15]:
# df['Transaction ID']=df['Transaction ID'].str[4:].astype(int) 1.mistake no need to create in num

In [16]:
df['Item'].unique()

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', 'UNKNOWN',
       'Sandwich', 'Unknown', 'ERROR', 'Juice', 'Tea'], dtype=object)

In [17]:
 # for i in F_order.index:
 #     df.drop(i,inplace=True)
# better way to delete these rows is 
df=df[df['Item'] != 'ERROR'].copy()

In [18]:
df['Item']=df['Item'].str.replace('UNKNOWN','Unknown')

In [19]:
df['Quantity'].unique()

array(['2', '4', '5', '3', '1', 'ERROR', 'UNKNOWN', 'Unknown'],
      dtype=object)

In [20]:
df['Quantity']=pd.to_numeric(df['Quantity'],errors='coerce')

In [21]:
# df['Quantity']=df['Quantity'].fillna(0 4.we dont know quantity

In [22]:
print(df['Quantity'].isna().sum())

461

In [23]:
df['Price Per Unit']=pd.to_numeric(df['Price Per Unit'],errors='coerce')

In [24]:
df['Total Spent']=pd.to_numeric(df['Total Spent'],errors='coerce')

In [25]:
# print(df['Total Spent'] / df['Price Per Unit'])

In [26]:
# df['Price Per Unit']=df['Price Per Unit'].fillna(0) 3.mistake

In [27]:
# df['Total Spent']=df['Total Spent'].fillna(0) 5 we dont know how it is

In [28]:
# df['Quantity']=df['Total Spent'] / df['Price Per Unit'] 2.mistake

In [29]:
# df['Quantity']=df['Quantity'].replace([np.inf,-np.inf,0],0)6 unnecessary

In [30]:
df.head(3)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,NaN,Credit Card,In-store,2023-07-19

In [31]:
# for i in na_orders.index:
#     df.drop(i,inplace=True)
# df=df[df['Quantity'] != 'ERROR'] 7 no need now its been na now

In [32]:
df['Payment Method'].unique()

array(['Credit Card', 'Cash', 'UNKNOWN', 'Digital Wallet', 'ERROR',
       'Unknown'], dtype=object)

In [33]:
a={'UNKNOWN':'Unknown',
   'ERROR':'Unknown'}
df['Payment Method']=df['Payment Method'].replace(a)

In [34]:
df['Location'].unique()

array(['Takeaway', 'In-store', 'UNKNOWN', 'Unknown', 'ERROR'],
      dtype=object)

In [35]:
df['Location']=df['Location'].str.replace('UNKNOWN','Unknown').str.replace('ERROR','Unknown')

In [36]:
a={'UNKNOWN':'Unknown',
   'ERROR':'Unknown'}
df['Transaction Date']=df['Transaction Date'].replace(a)

In [37]:
df[df['Transaction Date']=='Unknown']

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
11,TXN_3051279,Sandwich,2.0,4.0,8.0,Credit Card,Takeaway,Unknown
29,TXN_7640952,Cake,4.0,3.0,12.0,Digital Wallet,Takeaway,Unknown
33,TXN_7710508,Unknown,5.0,1.0,5.0,Cash,Unknown,Unknown
77,TXN_2091733,Salad,1.0,5.0,5.0,Unknown,In-store,Unknown
103,TXN_7028009,Cake,4.0,3.0,12.0,Unknown,Takeaway,Unknown
...,...,...,...,...,...,...,...,...
9933,TXN_9460419,Cake,1.0,3.0,3.0,Unknown,Takeaway,Unknown
9937,TXN_8253472,Cake,1.0,3.0,3.0,Unknown,Unknown,Unknown
9949,TXN_3130865,Juice,3.0,3.0,9.0,Unknown,In-store,Unknown
9983,TXN_9226047,Smoothie,3.0,4.0,12.0,Cash,Unknown,Unknown
9988,TXN_9594133,Cake,5.0,3.0,NaN,Unknown,Unknown,Unknown

In [38]:
df['Transaction Date']=pd.to_datetime(df['Transaction Date'],errors='coerce')

In [40]:
df['Transaction Date']=df['Transaction Date'].dt.strftime('%Y-%m-%d')

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9708 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9708 non-null   object
 1   Item              9708 non-null   object
 2   Quantity          9247 non-null   float64
 3   Price Per Unit    9188 non-null   float64
 4   Total Spent       9223 non-null   float64
 5   Payment Method    9708 non-null   object
 6   Location          9708 non-null   object
 7   Transaction Date  9257 non-null   object
dtypes: float64(3), object(5)
memory usage: 682.6+ KB

In [42]:
# df.reset_index(drop=True,inplace=True)

In [43]:
df.tail()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
9995,TXN_7672686,Coffee,2.0,2.0,4.0,Unknown,Unknown,2023-08-30
9996,TXN_9659401,Unknown,3.0,NaN,3.0,Digital Wallet,Unknown,2023-06-02
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,Unknown,2023-03-02
9998,TXN_7695629,Cookie,3.0,NaN,3.0,Digital Wallet,Unknown,2023-12-02
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07

In [45]:
print('Shape:',df.shape)
print('Duplicates:',df.duplicated().sum())
print('\n Missing Values:')
print(df.isna().sum())
print('\nData types:')
print(df.dtypes)

Shape: (9708, 8)
Duplicates: 0

 Missing Values:
Transaction ID        0
Item                  0
Quantity            461
Price Per Unit      520
Total Spent         485
Payment Method        0
Location              0
Transaction Date    451
dtype: int64

Data types:
Transaction ID       object
Item                 object
Quantity            float64
Price Per Unit      float64
Total Spent         float64
Payment Method       object
Location             object
Transaction Date     object
dtype: object

In [ ]:
# df.to_csv('D:\Github\python-data-preprocessing\Cafe dataset/Cleaned_dataset.csv',index=False)