In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('dirty_cafe_sales.csv')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [7]:
df.shape

(10000, 8)

In [8]:
df.describe()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_1961373,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

In [4]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [10]:
df.duplicated().sum()

0

In [13]:
text_columns=df.select_dtypes(include='object')
text_columns

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [26]:
for col in text_columns:
    df[col]=df[col].str.strip()

In [29]:
for col in text_columns:
    print(f"{col} : {df[col].isna().sum()}")

Transaction ID : 0
Item : 0
Quantity : 0
Price Per Unit : 0
Total Spent : 0
Payment Method : 0
Location : 0
Transaction Date : 0

In [28]:
for col in text_columns:
    df[col]=df[col].fillna('Unknown')

In [33]:
df.head(3)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19

In [37]:
df['Transaction ID'].duplicated().sum()

0

In [42]:
df['Transaction ID']=df['Transaction ID'].str[4:].astype(int)

In [54]:
df['Item'].unique()

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', 'Unknown',
       'Sandwich', 'Juice', 'Tea'], dtype=object)

In [47]:
#item name is error so it is false order
F_order=df[df['Item'] == 'ERROR']

In [50]:
 for i in F_order.index:
     df.drop(i,inplace=True)

In [53]:
df['Item']=df['Item'].str.replace('UNKNOWN','Unknown')

In [55]:
df['Quantity'].unique()

array(['2', '4', '5', '3', '1', 'ERROR', 'UNKNOWN', 'Unknown'],
      dtype=object)

In [58]:
#as per pattern we see total spent / price per unit is Quantity
E_quantity=df[df['Quantity']=='ERROR']

In [63]:
df['Quantity']=pd.to_numeric(df['Quantity'],errors='coerce')

In [66]:
df['Price Per Unit']=pd.to_numeric(df['Price Per Unit'],errors='coerce')

In [67]:
df['Total Spent']=pd.to_numeric(df['Total Spent'],errors='coerce')

In [74]:
# print(df['Total Spent'] / df['Price Per Unit'])

In [70]:
df['Price Per Unit']=df['Price Per Unit'].fillna(0)

In [71]:
df['Total Spent']=df['Total Spent'].fillna(0)

In [76]:
print(df['Quantity'].isna().sum())

461

In [77]:
df['Quantity']=df['Total Spent'] / df['Price Per Unit']

In [80]:
print(df['Quantity'].isna().sum())

19

In [83]:
df['Quantity']=df['Quantity'].replace([np.inf,-np.inf,0],0)

In [87]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,4271903,Cookie,0.0,1.0,0.0,Credit Card,In-store,2023-07-19
3,7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11