In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('trx-99.csv')

In [3]:
df.shape

(99, 6)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   status     99 non-null     object
 1   time       92 non-null     object
 2   card_type  96 non-null     object
 3   city       98 non-null     object
 4   amount     97 non-null     object
 5   id         99 non-null     int64
dtypes: int64(1), object(5)
memory usage: 4.8+ KB

In [5]:
df.describe()

               id
count   99.000000
mean    50.141414
std     28.935541
min      1.000000
25%     25.500000
50%     50.000000
75%     74.500000
max    100.000000

In [6]:
df.head()

    status              time card_type     city      amount  id
0  success  23:17 2025-09-08  Discover    ThRan       -5000   1
1   failed               NaN  MastCard    karaj       63489   2
2  success  07:32 2025-09-20      Visa  Isfahan     1502601   3
3   failed  03-00-2025 09-11  Discover      Qom  9999999999   4
4  success  22:27 2025-09-11      Amex  Mashhad      452545   5

In [7]:
text_column=df.select_dtypes(include='object')

In [8]:
for col in text_column:
    df[col]=df[col].str.strip()

In [9]:
for col in text_column:
    df[col]=df[col].fillna('Unknown')

In [10]:
df.duplicated().sum()

0

In [11]:
df.drop_duplicates()

     status              time    card_type     city      amount   id
0   success  23:17 2025-09-08     Discover    ThRan       -5000    1
1    failed           Unknown     MastCard    karaj       63489    2
2   success  07:32 2025-09-20         Visa  Isfahan     1502601    3
3    failed  03-00-2025 09-11     Discover      Qom  9999999999    4
4   success  22:27 2025-09-11         Amex  Mashhad      452545    5
..      ...               ...          ...      ...         ...  ...
94  Success  99:99 2025-13-40  Master-Card   TEHRAN           0   96
95     fail  21:23 2025-09-03         Amex   Tehran     1782689   97
96     fail  03:27 2025-09-12     Discover  Mashhad      914282   98
97     fail  19:51 2025-09-30     Discover    Ahvaz      914465   99
98  succeed    3pm 2025/09/11     Discover   tehr@n      585954  100

[99 rows x 6 columns]

In [12]:
df['status'].unique()

array(['success', 'failed', 'Success', 'fail', 'FAIL', 'succeed'],
      dtype=object)

In [13]:
change_status={'Success':'success',
               'succeed':'success',
               'FAIL':'fail',
              'failed':'fail'}

In [14]:
df['status']=df['status'].replace(change_status)
print(df['status'].unique())

['success' 'fail']

In [15]:
df['time']=pd.to_datetime(df['time'],errors='coerce')

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   status     99 non-null     object
 1   time       73 non-null     datetime64[ns]
 2   card_type  99 non-null     object
 3   city       99 non-null     object
 4   amount     99 non-null     object
 5   id         99 non-null     int64
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 4.8+ KB

In [17]:
df['time'].dt.strftime('%Y-%M-%D')

0     2025-17-09/08/25
1                  NaN
2     2025-32-09/20/25
3                  NaN
4     2025-27-09/11/25
            ...
94                 NaN
95    2025-23-09/03/25
96    2025-27-09/12/25
97    2025-51-09/30/25
98                 NaN
Name: time, Length: 99, dtype: object

In [18]:
df['card_type'].unique()

array(['Discover', 'MastCard', 'Visa', 'Amex', 'Master Card',
       'MasterCard', 'VISA', 'visa', 'Unknown', 'Master-Card', 'Vsa'],
      dtype=object)

In [19]:
df['card_type']=df['card_type'].str.lower()

In [20]:
df['card_type'].unique()

array(['discover', 'mastcard', 'visa', 'amex', 'master card',
       'mastercard', 'unknown', 'master-card', 'vsa'], dtype=object)

In [21]:
updated_cardname={'master card':'mastercard',
                  'mastcard':'mastercard',
                  'master-card':'mastercard',
                  'vsa':'visa'}

In [22]:
df['card_type']=df['card_type'].replace(updated_cardname)
print(df['card_type'].unique())

['discover' 'mastercard' 'visa' 'amex' 'unknown']

In [23]:
df['city']=df['city'].str.lower()

In [24]:
df['city'].unique()

array(['thran', 'karaj', 'isfahan', 'qom', 'mashhad', 'tehr@n', 'shiraz',
       'tehran', 'tabriz', 'ahvaz', 'thr', 'unknown'], dtype=object)

In [25]:
city_name={'ThRan':'tehran',
           'thran':'tehran',
           'tehr@n':'tehran',
           'thr':'tehran'}

In [26]:
df['city']=df['city'].replace(city_name)
print(df['city'].unique())

['tehran' 'karaj' 'isfahan' 'qom' 'mashhad' 'shiraz' 'tabriz' 'ahvaz'
 'unknown']

In [27]:
df['amount'].unique()

array(['-5000', '63489', '1502601', '9999999999', '452545', '1158713',
       '1387769', '583952', '1472823', '343679', '1768588', '443463',
       '100.50', '1883871', '1427657', 'one hundred', '1050805',
       '-999999', '0', '412308', '545116', '774681', '1', '99999',
       '205000', '5000', '585954', '177050', '250000', '-1', '1463119',
       '100000', '200000', '850000', '471227', '12345', '976246',
       '1578078', '419089', '1782689', '300000', '650000', '1305967',
       '50200', '900000', '450000', 'Unknown', '120000', '914282',
       '333333', '914465', '1000', '123456', '555555'], dtype=object)

In [28]:
df['amount']=df['amount'].str.replace(r'\D','',regex=True)

In [29]:
df['amount'].unique()

array(['5000', '63489', '1502601', '9999999999', '452545', '1158713',
       '1387769', '583952', '1472823', '343679', '1768588', '443463',
       '10050', '1883871', '1427657', '', '1050805', '999999', '0',
       '412308', '545116', '774681', '1', '99999', '205000', '585954',
       '177050', '250000', '1463119', '100000', '200000', '850000',
       '471227', '12345', '976246', '1578078', '419089', '1782689',
       '300000', '650000', '1305967', '50200', '900000', '450000',
       '120000', '914282', '333333', '914465', '1000', '123456', '555555'],
      dtype=object)

In [30]:
df=df[df['amount']!='9999999999'].copy()
df=df[df['amount']!='1'].copy()

In [31]:
df['amount'].max()

'999999'

In [32]:
df['amount'].astype(int)

ValueError: invalid literal for int() with base 10: ''

In [ ]:
df['id'].unique()

In [ ]:
print('Shape:',df.shape)
print('Duplicates:',df.duplicated().sum())
print('\n Missing Values:')
print(df.isna().sum())
print('\nData types:')
print(df.dtypes)