In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('trx-99.csv')

In [3]:
df.shape

(99, 6)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   status     99 non-null     object
 1   time       92 non-null     object
 2   card_type  96 non-null     object
 3   city       98 non-null     object
 4   amount     97 non-null     object
 5   id         99 non-null     int64
dtypes: int64(1), object(5)
memory usage: 4.8+ KB

In [5]:
df.describe()

               id
count   99.000000
mean    50.141414
std     28.935541
min      1.000000
25%     25.500000
50%     50.000000
75%     74.500000
max    100.000000

In [6]:
df.head()

    status              time card_type     city      amount  id
0  success  23:17 2025-09-08  Discover    ThRan       -5000   1
1   failed               NaN  MastCard    karaj       63489   2
2  success  07:32 2025-09-20      Visa  Isfahan     1502601   3
3   failed  03-00-2025 09-11  Discover      Qom  9999999999   4
4  success  22:27 2025-09-11      Amex  Mashhad      452545   5

In [7]:
text_column=df.select_dtypes(include='object')

In [8]:
for col in text_column:
    df[col]=df[col].str.strip()

In [9]:
for col in text_column:
    df[col]=df[col].fillna('Unknown')

In [10]:
df.duplicated().sum()

0

In [11]:
df.drop_duplicates()

     status              time    card_type     city      amount   id
0   success  23:17 2025-09-08     Discover    ThRan       -5000    1
1    failed           Unknown     MastCard    karaj       63489    2
2   success  07:32 2025-09-20         Visa  Isfahan     1502601    3
3    failed  03-00-2025 09-11     Discover      Qom  9999999999    4
4   success  22:27 2025-09-11         Amex  Mashhad      452545    5
..      ...               ...          ...      ...         ...  ...
94  Success  99:99 2025-13-40  Master-Card   TEHRAN           0   96
95     fail  21:23 2025-09-03         Amex   Tehran     1782689   97
96     fail  03:27 2025-09-12     Discover  Mashhad      914282   98
97     fail  19:51 2025-09-30     Discover    Ahvaz      914465   99
98  succeed    3pm 2025/09/11     Discover   tehr@n      585954  100

[99 rows x 6 columns]

In [12]:
df['status'].unique()

array(['success', 'failed', 'Success', 'fail', 'FAIL', 'succeed'],
      dtype=object)

In [13]:
change_status={'Success':'success',
               'succeed':'success',
               'FAIL':'fail',
              'failed':'fail'}

In [14]:
df['status']=df['status'].replace(change_status)
print(df['status'].unique())

['success' 'fail']

In [15]:
df['time']=pd.to_datetime(df['time'],format='%H:%M %Y-%m-%d',errors='coerce')

In [16]:
df['card_type'].unique()

array(['Discover', 'MastCard', 'Visa', 'Amex', 'Master Card',
       'MasterCard', 'VISA', 'visa', 'Unknown', 'Master-Card', 'Vsa'],
      dtype=object)

In [17]:
df['card_type']=df['card_type'].str.lower()

In [18]:
df['card_type'].unique()

array(['discover', 'mastcard', 'visa', 'amex', 'master card',
       'mastercard', 'unknown', 'master-card', 'vsa'], dtype=object)

In [19]:
updated_cardname={'master card':'mastercard',
                  'mastcard':'mastercard',
                  'master-card':'mastercard',
                  'vsa':'visa'}

In [20]:
df['card_type']=df['card_type'].replace(updated_cardname)
print(df['card_type'].unique())

['discover' 'mastercard' 'visa' 'amex' 'unknown']

In [21]:
df['city']=df['city'].str.lower()

In [22]:
df['city'].unique()

array(['thran', 'karaj', 'isfahan', 'qom', 'mashhad', 'tehr@n', 'shiraz',
       'tehran', 'tabriz', 'ahvaz', 'thr', 'unknown'], dtype=object)

In [23]:
city_name={'ThRan':'tehran',
           'thran':'tehran',
           'tehr@n':'tehran',
           'thr':'tehran'}

In [24]:
df['city']=df['city'].replace(city_name)
print(df['city'].unique())

['tehran' 'karaj' 'isfahan' 'qom' 'mashhad' 'shiraz' 'tabriz' 'ahvaz'
 'unknown']

In [25]:
df['amount'].unique()

array(['-5000', '63489', '1502601', '9999999999', '452545', '1158713',
       '1387769', '583952', '1472823', '343679', '1768588', '443463',
       '100.50', '1883871', '1427657', 'one hundred', '1050805',
       '-999999', '0', '412308', '545116', '774681', '1', '99999',
       '205000', '5000', '585954', '177050', '250000', '-1', '1463119',
       '100000', '200000', '850000', '471227', '12345', '976246',
       '1578078', '419089', '1782689', '300000', '650000', '1305967',
       '50200', '900000', '450000', 'Unknown', '120000', '914282',
       '333333', '914465', '1000', '123456', '555555'], dtype=object)

In [26]:
df['amount']=df['amount'].str.replace(r'\D','',regex=True)
df['amount']=pd.to_numeric(df['amount'],errors='coerce').fillna(0)

In [27]:
df['amount'].unique()

array([5.000000e+03, 6.348900e+04, 1.502601e+06, 1.000000e+10,
       4.525450e+05, 1.158713e+06, 1.387769e+06, 5.839520e+05,
       1.472823e+06, 3.436790e+05, 1.768588e+06, 4.434630e+05,
       1.005000e+04, 1.883871e+06, 1.427657e+06, 0.000000e+00,
       1.050805e+06, 9.999990e+05, 4.123080e+05, 5.451160e+05,
       7.746810e+05, 1.000000e+00, 9.999900e+04, 2.050000e+05,
       5.859540e+05, 1.770500e+05, 2.500000e+05, 1.463119e+06,
       1.000000e+05, 2.000000e+05, 8.500000e+05, 4.712270e+05,
       1.234500e+04, 9.762460e+05, 1.578078e+06, 4.190890e+05,
       1.782689e+06, 3.000000e+05, 6.500000e+05, 1.305967e+06,
       5.020000e+04, 9.000000e+05, 4.500000e+05, 1.200000e+05,
       9.142820e+05, 3.333330e+05, 9.144650e+05, 1.000000e+03,
       1.234560e+05, 5.555550e+05])

In [28]:
print(df['amount'].max())
df=df[df['amount'] != 9999999999].copy()

9999999999.0

In [29]:
df['amount'].astype(int)

0        5000
1       63489
2     1502601
4      452545
6     1158713
       ...
94          0
95    1782689
96     914282
97     914465
98     585954
Name: amount, Length: 96, dtype: int32

In [30]:
df['amount'].unique()

array([5.000000e+03, 6.348900e+04, 1.502601e+06, 4.525450e+05,
       1.158713e+06, 1.387769e+06, 5.839520e+05, 1.472823e+06,
       3.436790e+05, 1.768588e+06, 4.434630e+05, 1.005000e+04,
       1.883871e+06, 1.427657e+06, 0.000000e+00, 1.050805e+06,
       9.999990e+05, 4.123080e+05, 5.451160e+05, 7.746810e+05,
       1.000000e+00, 9.999900e+04, 2.050000e+05, 5.859540e+05,
       1.770500e+05, 2.500000e+05, 1.463119e+06, 1.000000e+05,
       2.000000e+05, 8.500000e+05, 4.712270e+05, 1.234500e+04,
       9.762460e+05, 1.578078e+06, 4.190890e+05, 1.782689e+06,
       3.000000e+05, 6.500000e+05, 1.305967e+06, 5.020000e+04,
       9.000000e+05, 4.500000e+05, 1.200000e+05, 9.142820e+05,
       3.333330e+05, 9.144650e+05, 1.000000e+03, 1.234560e+05,
       5.555550e+05])

In [31]:
df['id'].unique()

array([  1,   2,   3,   5,   7,   8,   9,  10,  11,  12,  13,  14,  15,
        16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
        29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
        42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,
        55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,
        68,  69,  70,  71,  72,  73,  74,  76,  77,  78,  79,  80,  81,
        82,  83,  84,  85,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100], dtype=int64)

In [32]:
print('Shape:',df.shape)
print('Duplicates:',df.duplicated().sum())
print('\n Missing Values:')
print(df.isna().sum())
print('\nData types:')
print(df.dtypes)

Shape: (96, 6)
Duplicates: 0

 Missing Values:
status        0
time         25
card_type     0
city          0
amount        0
id            0
dtype: int64

Data types:
status               object
time         datetime64[ns]
card_type            object
city                 object
amount              float64
id                    int64
dtype: object

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 96 entries, 0 to 98
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   status     96 non-null     object
 1   time       71 non-null     datetime64[ns]
 2   card_type  96 non-null     object
 3   city       96 non-null     object
 4   amount     96 non-null     float64
 5   id         96 non-null     int64
dtypes: datetime64[ns](1), float64(1), int64(1), object(3)
memory usage: 5.2+ KB

In [35]:
df.reset_index(drop=True,inplace=True)

In [36]:
df.to_csv('D:\Github\python-data-preprocessing\Iranian_airlines-ds/cleaned_dataset.csv',index=False)